### PR TITLE
Set Up

### PR DESCRIPTION
**Pull request by Hakshay-Sundar**
This branch has the base code set up for everyone to use. 
I have set up the basic definition of the following

1. Node
2. Edge
3. Graph

There is a function to show a dummy network being created as well. 
It adds 5 nodes: A which is the current head and is adjacent to B, C, D, and E. 
There is an NxN matrix for edges. This simply tracks the edge weights between 2 locations. 
We simply need to pull the neighbor list for each node and get the weights from the matrix. 
This implementation has both an adjacency list and an adjacency matrix for our ease. 

The matrix will allow for faster edge tracking whereas the list would enable us to get all the neighbors for a particular node much quicker. 

Attached is an image to show the sample response for this. 
Screenshot 2023-11-27 at 3 50 00 PM

Please note that once we create the graph that we need, this will be a constant function that is invoked at the start of each run. 
Our focus will then shift to running our algorithm.

### CODE REVIEW

**Review by snowclipsed — CHANGES_REQUESTED** [review]
I think the starter code is a good representative of what direction we want to head into. However, I have a few comments regarding the general structure of the code and I question the usage of certain coding practices (pointing them now since this is our technical base and the earlier they get resolved the better).

- Organize main class at top
- Helper functions at bottom
- Explain "Dull" and "Vibrant", though I assume that would be done in the README.


Tasks I would like for us to implement in the near future in an order of priority:
- organized classes for each type of graph (adj matrix, adj list based)
- add adj list based graphs.
- a way for the user to CRUD the nodes into the program allowing them to test multiple scenarios, console input should work for now.
- unsymmetric matrix support
- implement basic UI elements using networkx and plotly/matplotlib

**Comment by Hakshay-Sundar** [comment]
> I think the starter code is a good representative of what direction we want to head into. However, I have a few comments regarding the general structure of the code and I question the usage of certain coding practices (pointing them now since this is our technical base and the earlier they get resolved the better).
> 
> * Organize main class at top
> * Helper functions at bottom
> * Explain "Dull" and "Vibrant", though I assume that would be done in the README.
> 
> Tasks I would like for us to implement in the near future in an order of priority:
> 
> * organized classes for each type of graph (adj matrix, adj list based)
> * add adj list based graphs.
> * a way for the user to CRUD the nodes into the program allowing them to test multiple scenarios, console input should work for now.
> * unsymmetric matrix support
> * implement basic UI elements using networkx and plotly/matplotlib

The changes are made such that the main function is on top. 
However, we need to keep in mind that this main function is just for our convenience at the moment and will be removed since the code architecture is yet to be set up as we build more features on top of that. 

Additionally, the definitions of Dull and Vibrant have already been given in the comments for each class that was defined. 

I would like to highlight that the future scope of our work will be determined based on our meeting today (28th November 2023). We will assign tasks such that our project will collectively move ahead to completion since we have 2 weeks left. We will have to triage and drop ideas that might be too far-fetched given the time that we have. 

P.S: Let us not block reviews with future prospects. Let us only block it with respect to the task at hand and the changes needed for that particular task.

**Review by snowclipsed — APPROVED** [review]

**Review by Saanidhyavats — APPROVED** [review]
Good from my side!

**Review by rashaadmirza — APPROVED** [review]
The overall progress looks impressive. Suggesting an improvement at line 79, I feel we can enhance code clarity.

**Pull request merged**
